name: Daily VC Lead Generator

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Lead Generator Script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python lead_gen.py

      - name: Upload Daily CSV Artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-vc-leads
          path: vc_podcast_leads_*.csv  # ✅ Corrected filename

      - name: Upload Updated History
        uses: actions/upload-artifact@v4
        with:
          name: vc-lead-history
          path: history.csv
